# Generated by Django 5.2.5 on 2025-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
