# Generated by Django 5.2.5 on 2025-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_batch_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='condition',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
