# Generated by Django 5.2.5 on 2025-12-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_batch_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='icon',
        ),
        migrations.AlterField(
            model_name='batch',
            name='condition',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
